version: '3'

services:
  backend:
    build:
      context: .
    container_name: 'demo-backend-springboot'
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    depends_on:
        - db
    command: sh start-backend.sh
  db:
    build: ./db
    container_name: 'demo-database-postgres'
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=student
volumes:
  db: